### ISSUE TITLE
the processing code for ESConv can't be found

### ISSUE THREAD

**Issue by LTC232** [lwgkzl/MultiESC#1]
Can you provide the processing code for ESConv

**Comment by lwgkzl** [comment]
The data processing process has gone through multiple versions, making it difficult to provide code for data processing. Perhaps it would be better for you to directly use the dataset we provide

**Comment by YiCheng98** [comment]
The major differences between our preprocessed data and the original ESConv dataset published with[ the ACL 2021 paper from Liu et al. ](https://arxiv.org/pdf/2106.01144.pdf) are as follows:

1. Their originally published dataset includes 1053 dialogues, while our experiments further include their later released 247 conversations at [github](https://github.com/thu-coai/Emotional-Support-Conversation). In total, there are 1,300 dialogues for our experiments. We randomly distribute 910/195/195 dialogues into the training/validation/testing sets.

2. In the original dataset, there are many cases where the adjacent utterances are from the same interlocutor, as this dataset was constructed through online chatting and it was allowed to send multiple messages in succession. However, we do not deem it necessary to require the dialogue system to learn the division of multiple successive messages, so we merge the adjacent utterances in such cases into one. Consequently, the conversation in the preprocessed data has an average of 23.4 dialogue turns.

3. Some adaptions are conducted on the strategy annotation, which was illustrated in the appendix of [our paper](https://aclanthology.org/2022.emnlp-main.195.pdf). 
- First, we find that the definitions of _Providing Suggestions_ and _Information_ are often hard to differentiate, and the annotation in some cases is also confusing (some examples are shown in the paper). Thus, we merge these two categories into one type of strategy, named “Providing Suggestions or Information”. 
- Second, we find that the existence of the “Others” category largely impedes the model performance. Many utterances in this category are in fact exchange of pleasantries, while many others actually can be categorized into one particular strategy but not, probably due to the annotators' incaution. Since the exchange of pleasantries is also an essential strategy that helps to establish a friendly connection with the user, we define a new strategy category, named “_Greetings_” for such kinds of responses. We obtain the annotation of them by first using a set of regular expression matches and then manually double-checking the results.
- Since this part of preprocessing includes several revision rounds and involves manual corrections, it is hard to provide codes directly leading to our preprocessed results. You might directly use our preprocessed data for experiments. Thanks for your understanding.

**Comment by NirmalManoj** [comment]
> * We randomly distribute 1040/130/130 dialogues into the training/validation/testing sets.

But the split provided in this repository is 910/195/195. Why is that?

**Comment by Wh2018** [comment]
- We randomly distribute 1040/130/130 dialogues into the training/validation/testing sets.

I have the same doubt, the data provided in the repo is not divided in 8:1:1, with 910/195/195. What kind of split did you use in your experiment?

**Comment by YiCheng98** [comment]
Thank you, @NirmalManoj and @Wh2018, for bringing the mistake to our attention. We have reviewed the issue and made the necessary corrections. After confirmation, we did split the dataset into 910/195/195.

The data provided in our GitHub repository is exactly what we used for training, validation, and testing.

**Comment by Wh2018** [comment]
> Thank you, @NirmalManoj and @Wh2018, for bringing the mistake to our attention. We have reviewed the issue and made the necessary corrections. After confirmation, we did split the dataset into 910/195/195.
> 
> The data provided in our GitHub repository is exactly what we used for training, validation, and testing.

Thank you for your reply！ I still have a question, if the dataset is divided into 910/195/195 then the ratio is about 4.6:1:1, is this ratio normal in experiments？
